on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - name: install elan
      run: |
        set -o pipefail
        curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH

    - name: checkout project
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: get Mathlib4 cache
      run: lake exe cache get

    - name: build library
      id: build
      continue-on-error: true
      run: |
        lake build Library
        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
        fi

    - name: Check build status
      if: steps.build.outputs.status == 'failure'
      run: |
        echo "::error::Lean compilation failed. Please check your code for errors."
        exit 1